const MANGA_URLS=['data/manhwas.json','manhwas.json'];
const CHAPTERS_URLS=['data/mangas_resultado.json','mangas_resultado.json'];
const STORAGE_KEY='portal_manhwas_progress_v2',THEME_KEY='portal_manhwas_theme';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search);
const mangaId=params.get('id')||'',urlTitle=params.get('title')||'';
let state=loadState(),manga=null,chapters=[],q='',filter='todos';
const clean=t=>String(t||'').replace(/\|\s*Blackout Comics/ig,'').trim();
const slug=t=>clean(t).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const keyOf=m=>String(m.id??m.url??slug(m.title||m.titulo||m.nome));
function loadState(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return {}}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function getProgress(id){state[id] ||= {read:[],current:0,favorite:false,finished:false};return state[id]}
async function readJson(urls,fallback){for(const url of urls){try{const r=await fetch(url,{cache:'no-store'});if(r.ok)return await r.json()}catch{}}return fallback}
function normalizeManga(item,i){const title=clean(item.titulo||item.nome||item.title||`Manhwa ${i+1}`);const id=String(item.id??'').trim()||(String(item.url||item.link||'').match(/\/comics\/(\d+)/)?.[1]);return{id:id||String(i),title,url:item.url||item.link||'',cover:item.capa||item.imagem||item.cover||'',status:item.status||'unknown'}}
const numbers=list=>(Array.isArray(list)?list:[]).map(c=>Number(String(c).match(/\d+/)?.[0]||c)).filter(Boolean).sort((a,b)=>a-b);
async function init(){if(localStorage.getItem(THEME_KEY)==='light')document.documentElement.classList.add('light');$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem(THEME_KEY,document.documentElement.classList.contains('light')?'light':'dark')};const [mRaw,cRaw]=await Promise.all([readJson(MANGA_URLS,[]),readJson(CHAPTERS_URLS,[])]);const mangas=(mRaw||[]).map(normalizeManga);manga=mangas.find(m=>String(m.id)===String(mangaId))||mangas.find(m=>slug(m.title)===slug(urlTitle))||{id:mangaId,title:urlTitle||'Obra',cover:'',status:'unknown'};const entry=(cRaw||[]).find(item=>String(item.id??(String(item.url||item.link||'').match(/\/comics\/(\d+)/)?.[1]||''))===String(manga.id))||(cRaw||[]).find(item=>slug(item.nome||item.titulo||'')===slug(manga.title));chapters=numbers(entry?.capitulos);renderHeader();renderChapters();bindControls()}
function renderHeader(){const p=getProgress(keyOf(manga));const percent=chapters.length?Math.round((p.read.length/chapters.length)*100):0;document.title=`${manga.title} • Portal Manhwas`;$('#mangaHeader').innerHTML=`<div class="manga-cover">${manga.cover?`<img src="${manga.cover}" alt="${manga.title}" onerror="this.replaceWith(placeholderCover('${manga.title.replace(/'/g,'')}'))">`:`<div class="cover-placeholder">${manga.title[0]||'M'}</div>`}</div><div class="manga-title"><p class="eyebrow">Detalhes da obra</p><h1>${manga.title}</h1><div class="pill-row"><span class="pill">${chapters.length} capítulos</span><span class="pill">${p.read.length} lidos</span><span class="pill">${percent}% completo</span><span class="pill">${p.finished?'Finalizado':'Em andamento'}</span></div><div class="progress"><i style="width:${percent}%"></i></div><div class="card-actions" style="max-width:360px"><button class="small-btn" id="favBtn">${p.favorite?'★ Favorito':'☆ Favoritar'}</button><button class="small-btn" id="finishBtn">${p.finished?'Reabrir':'Finalizar'}</button></div></div>`;$('#favBtn').onclick=()=>{p.favorite=!p.favorite;saveState();renderHeader()};$('#finishBtn').onclick=()=>{p.finished=!p.finished;saveState();renderHeader()}}
window.placeholderCover=title=>{const div=document.createElement('div');div.className='cover-placeholder';div.textContent=title?.[0]||'M';return div};
function bindControls(){$('#chapterSearch').oninput=e=>{q=e.target.value.toLowerCase().trim();renderChapters()};$('#chapterFilter').onchange=e=>{filter=e.target.value;renderChapters()};$('#markAllBtn').onclick=()=>{const p=getProgress(keyOf(manga));p.read=[...new Set([...p.read,...chapters])];p.current=chapters.at(-1)||p.current;saveState();renderHeader();renderChapters()}}
function renderChapters(){const p=getProgress(keyOf(manga));let list=chapters.filter(c=>String(c).includes(q));list=list.filter(c=>filter==='lidos'?p.read.includes(c):filter==='nao-lidos'?!p.read.includes(c):true);$('#chaptersGrid').innerHTML=list.map(c=>`<a class="chapter-card card ${p.read.includes(c)?'read':''}" href="leitor.html?id=${encodeURIComponent(manga.id)}&title=${encodeURIComponent(manga.title)}&cap=${c}"><strong>Capítulo ${c}</strong><span>${p.read.includes(c)?'Lido':'Abrir'}</span></a>`).join('');$('#emptyState').classList.toggle('hidden',list.length>0)}
init();
