name: Atualizar Manhwas Automaticamente

on:
  schedule:
    - cron: '0 9 * * *' # Roda todo dia às 09:00 UTC
  workflow_dispatch: # Isso cria o botão "Run workflow" para você testar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Rodar scanner
        run: python scanner.py

      - name: Enviar mudanças para o repositório
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add manhwas.json
          git commit -m "Atualizacao automatica do JSON de manhwas"
          git push
